# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box_url = 'http://developer.nrel.gov/downloads/vagrant-boxes/CentOS-6.4-x86_64-v20130427.box'
  config.vm.box = 'centos6'

  config.vm.define :web do |config|
    config.vm.network :private_network, ip: '192.168.33.215'
  end

  config.vm.define :mysql do |config|
    config.vm.network :private_network, ip: '192.168.33.216'
  end
end
